# Generated by Django 5.2 on 2025-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_courier_delivery_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dest_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
