# Generated by Django 5.2 on 2025-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_dest_lat_delivery_dest_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='dest_lat',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='dest_lon',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='source_lat',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='source_lon',
        ),
    ]
