# Generated by Django 5.2 on 2025-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_dest_lat_remove_delivery_dest_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dest_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
